name: z2test_gha

on:
  workflow_dispatch:
  push:
    tags:
     - '*'

env:
  REGISTRY: ghcr.io


jobs:
  ci_step:
    name: Build, tag and push image to registry
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      -
        name: Metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/zadanie2_test
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3


      - 
        name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: echo "token: $GITHUB_TOKEN"

      - 
        name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ github.actor }}/zadanie2_test:cache 
          cache-to: |
            type=registry,ref=${{ github.actor }}/zadanie2_test:cache  
          tags: ${{ steps.meta.outputs.tags }}

    
                 
